export const GET_PRODUCTOS_AUTO = 'GET_PRODUCTOS_AUTO';
export const GET_PRODUCTOS_MOTO = 'GET_PRODUCTOS_MOTO';
export const GET_PRODUCTOS_REPUESTO = 'GET_PRODUCTOS_REPUESTO';
export const BUSCAR_PRODUCTOS_AUTO = 'BUSCAR_PRODUCTOS_AUTO';
export const BUSCAR_PRODUCTOS_MOTO = 'BUSCAR_PRODUCTOS_MOTO';
export const BUSCAR_PRODUCTOS_REPUESTO = 'BUSCAR_PRODUCTOS_REPUESTO';